module.exports = {
  name: "inbox",
  port: 3009,
  exposes: {
    "./routes": "./src/routes.tsx",
    "./settings": "./src/Settings.tsx",
  },
  routes: {
    url: "http://localhost:3009/remoteEntry.js",
    scope: "inbox",
    module: "./routes",
  },
  menus: [
    {
      text: "Team Inbox",
      url: "/inbox",
      icon: "icon-comment-1",
      location: "mainNavigation",
    },
    {
      text: "Bookings",
      url: "/bookings",
      icon: "icon-paste",
      location: "mainNavigation",
    },
    {
      text: "Forms",
      url: "/forms",
      icon: "icon-head-1",
      location: "mainNavigation",
    },
    {
      text: "Skills",
      icon: "icon-file-info-alt",
      location: "settings",
      scope: "plugins",
      component: "./settings",
      name: "Skills",
      image: "/images/icons/erxes-29.png",
      to: "/settings/skills",
      action: "skillTypesAll",
      permissions: [
        "getSkillTypes",
        "getSkill",
        "getSkills",
        "manageSkills",
        "manageSkillTypes",
      ],
    },
    {
      text: "Channels",
      icon: "icon-layer-group",
      location: "settings",
      scope: "plugins",
      component: "./settings",
      name: "Channels",
      image: "/images/icons/erxes-05.svg",
      to: "/settings/channels",
      action: "channelsAll",
      permissions: ["showChannels", "manageChannels"],
    },
    {
      text: "Integrations",
      icon: "icon-puzzle-piece",
      location: "settings",
      scope: "plugins",
      component: "./settings",
      name: "Integrations",
      image: "/images/icons/erxes-04.svg",
      to: "/settings/integrations",
      action: "integrationsAll",
      permissions: [
        "showIntegrations",
        "integrationsCreateMessengerIntegration",
        "integrationsEditMessengerIntegration",
        "integrationsSaveMessengerAppearanceData",
        "integrationsSaveMessengerConfigs",
        "integrationsCreateLeadIntegration",
        "integrationsEditLeadIntegration",
        "integrationsRemove",
        "integrationsArchive",
        "integrationsEdit",
      ],
    },
    {
      text: "Responses",
      icon: "icon-files-landscapes",
      location: "settings",
      scope: "plugins",
      component: "./settings",
      name: "Response Template",
      image: "/images/icons/erxes-10.svg",
      to: "/settings/response-templates",
      action: "responseTemplatesAll",
      permissions: ['manageResponseTemplate', 'showResponseTemplates']
    },
  ],
};
