module.exports = {
  name: "deals",
  port: 3003,
  exposes: {
    "./routes": "./src/routes.tsx",
    "./settings": "./src/Settings.tsx",
  },
  routes: {
    url: "http://localhost:3003/remoteEntry.js",
    scope: "deals",
    module: "./routes",
  },
  menus: [
    // {
    //   text: 'Sales Pipeline',
    //   url: '/deal',
    //   icon: 'icon-piggy-bank',
    //   location: 'mainNavigation'
    // },
    // {
    //   text: 'Task',
    //   url: '/task',
    //   icon: 'icon-laptop',
    //   location: 'mainNavigation'
    // },
    // {
    //   text: 'Ticket',
    //   url: '/ticket/board',
    //   icon: 'icon-ticket',
    //   location: 'mainNavigation'
    // }
    {
      text: "Growth Hacking",
      url: "/growthHack",
      icon: "icon-idea",
      location: "mainNavigation",
    },
    {
      text: "Sales pipelines",
      icon: "icon-calendar-alt",
      location: "settings",
      scope: "plugins",
      component: "./settings",
      name: "Sales Pipelines",
      image: "/images/icons/erxes-25.png",
      to: "/settings/boards/deal",
      action: "dealsAll",
      permissions: [
        "dealBoardsAdd",
        "dealBoardsEdit",
        "dealBoardsRemove",
        "dealPipelinesAdd",
        "dealPipelinesEdit",
        "dealPipelinesUpdateOrder",
        "dealPipelinesRemove",
        "dealPipelinesArchive",
        "dealPipelinesArchive",
        "dealStagesAdd",
        "dealStagesEdit",
        "dealStagesUpdateOrder",
        "dealStagesRemove",
      ],
    },
    {
      text: "Task pipelines",
      icon: "icon-calendar-alt",
      location: "settings",
      scope: "plugins",
      component: "./settings",
      name: "Task Pipelines",
      image: "/images/icons/erxes-13.svg",
      to: "/settings/boards/task",
      action: "tasksAll",
      permissions: [
        "taskBoardsAdd",
        "taskBoardsEdit",
        "taskBoardsRemove",
        "taskPipelinesAdd",
        "taskPipelinesEdit",
        "taskPipelinesUpdateOrder",
        "taskPipelinesRemove",
        "taskPipelinesArchive",
        "taskPipelinesCopied",
        "taskStagesAdd",
        "taskStagesEdit",
        "taskStagesUpdateOrder",
        "taskStagesRemove",
        "tasksAll",
      ],
    },
    {
      text: "Ticket pipelines",
      icon: "icon-calendar-alt",
      location: "settings",
      scope: "plugins",
      component: "./settings",
      name: "Ticket Pipelines",
      image: "/images/icons/erxes-19.svg",
      to: "/settings/boards/ticket",
      action: "ticketsAll",
      permissions: [
        "ticketBoardsAdd",
        "ticketBoardsEdit",
        "ticketBoardsRemove",
        "ticketPipelinesAdd",
        "ticketPipelinesEdit",
        "ticketPipelinesUpdateOrder",
        "ticketPipelinesRemove",
        "ticketPipelinesArchive",
        "ticketPipelinesCopied",
        "ticketStagesAdd",
        "ticketStagesEdit",
        "ticketStagesUpdateOrder",
        "ticketStagesRemove",
      ],
    },
    {
      text: "Growth Hacking",
      location: "settings",
      scope: "plugins",
      component: "./settings",
      name: "Growth Hacking",
      image: "/images/icons/erxes-20.svg",
      to: "/settings/boards/growthHack",
      action: "growthHacksAll",
      permissions: [
        "growthHackBoardsAdd",
        "growthHackBoardsEdit",
        "growthHackBoardsRemove",
        "growthHackPipelinesAdd",
        "growthHackPipelinesEdit",
        "growthHackPipelinesUpdateOrder",
        "growthHackPipelinesRemove",
        "growthHackPipelinesArchive",
        "growthHackPipelinesCopied",
        "growthHackStagesAdd",
        "growthHackStagesEdit",
        "growthHackStagesUpdateOrder",
        "growthHackStagesRemove",
      ],
    },
  ],
};
